# Generated by Django 4.1.3 on 2022-11-02 21:24

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Transaction creation date.')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.TextField(default='EUR', help_text='Currency of the transaction.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[common.validators.validate_positive])),
                ('data', models.JSONField()),
                ('type', models.TextField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
