# Generated by Django 4.1.3 on 2022-11-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for the transaction.'),
        ),
    ]
